Documentation:
  Enabled: false
LineLength:
  Max: 80

AllCops:
  RunRailsCops: true
  Include:
    - lib/tasks/*
  Exclude:
    - bin/*
    - db/migrations
    - db/migrate/*
    - db/schema.rb
    - vendor/**/*
